# -*- coding: utf-8 -*-
"""BESS_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1euFAzHRA4ED7_DnuPTAPiyiut7UYHqcL
"""

import pandas as pd

# ==========================================
# 1. ΦΟΡΤΩΣΗ ΔΕΔΟΜΕΝΩΝ
# ==========================================
df_prices = pd.read_csv('Price per hour.csv', sep=';', decimal=',')
df_production = pd.read_csv('Energy per hour.csv', sep=';', decimal=',', header=None)


# ==========================================
# 2. ΚΑΘΑΡΙΣΜΟΣ ΠΑΡΑΓΩΓΗΣ (PVsyst)
# ==========================================
df_production.columns = ['PVsyst_Time', 'Energy_W']
# Μετατροπή W σε MW
df_production['Energy_MW'] = df_production['Energy_W'] / 1000000
# Ορισμός στήλης ωρών (Datetime)
df_production['Datetime'] = pd.date_range(start='2025-01-01 00:00', periods=8760, freq='h')
df_production.set_index('Datetime', inplace=True)


# ==========================================
# 3. ΚΑΘΑΡΙΣΜΟΣ ΑΓΟΡΑΣ (ENTSO-E)
# ==========================================
df_prices.columns = df_prices.columns.str.strip()

# Βρίσκουμε δυναμικά τα ονόματα των στηλών
time_col = df_prices.columns[0]  # Η 1η στήλη (Ημερομηνία)
price_col = df_prices.columns[1] # Η 2η στήλη (Τιμή)

# Μετατρέπουμε την τιμή σε καθαρό αριθμό
df_prices[price_col] = pd.to_numeric(df_prices[price_col].astype(str).str.replace(',', '.'), errors='coerce')

# Φτιάχνουμε το Datetime κρατώντας τους πρώτους 19 χαρακτήρες
df_prices['Datetime'] = df_prices[time_col].astype(str).str.split(' - ').str[0].str.strip().str[:19]
df_prices['Datetime'] = pd.to_datetime(df_prices['Datetime'], format='%d/%m/%Y %H:%M:%S', errors='coerce')
df_prices.set_index('Datetime', inplace=True)

# Ομαδοποίηση δεδομένων ανά ώρα
df_prices_hourly = df_prices.resample('h').mean(numeric_only=True)


# ==========================================
# 4. ΕΝΩΣΗ
# ==========================================
df_final = pd.concat([df_production['Energy_MW'], df_prices_hourly[price_col]], axis=1)
df_final.columns = ['Solar_MW', 'Price_EUR_MWh']

print("Το τελικό, ενωμένο DataFrame (8.760 ώρες):")
display(df_final)

import matplotlib.pyplot as plt

# Φιλτράρουμε τα δεδομένα για μια ανοιξιάτικη εβδομάδα (π.χ. 10 με 16 Απριλίου)
df_spring = df_final.loc['2025-04-10':'2025-04-16']

# Στήνουμε τον "καμβά" του γραφήματος
fig, ax1 = plt.subplots(figsize=(12, 6))

# Πρώτος Άξονας (Αριστερά): Παραγωγή Φ/Β (Πορτοκαλί)
color_solar = 'darkorange'
ax1.set_xlabel('Ημερομηνία', fontweight='bold')
ax1.set_ylabel('Παραγωγή Φ/Β (MW)', color=color_solar, fontweight='bold')
# Γεμίζουμε με χρώμα κάτω από τη γραμμή
ax1.plot(df_spring.index, df_spring['Solar_MW'], color=color_solar, linewidth=2)
ax1.fill_between(df_spring.index, df_spring['Solar_MW'], color=color_solar, alpha=0.3)
ax1.tick_params(axis='y', labelcolor=color_solar)

# Δεύτερος Άξονας (Δεξιά): Τιμή DAM (Μπλε)
# Η εντολή twinx() φτιάχνει έναν δεύτερο άξονα y που μοιράζεται τον ίδιο άξονα x
ax2 = ax1.twinx()
color_price = 'navy'
ax2.set_ylabel('Τιμή ρεύματος (EUR/MWh)', color=color_price, fontweight='bold')
# Σχεδιάζουμε την τιμή με διακεκομμένη γραμμή για να ξεχωρίζει
ax2.plot(df_spring.index, df_spring['Price_EUR_MWh'], color=color_price, linewidth=2, linestyle='--')
ax2.tick_params(axis='y', labelcolor=color_price)

# Προσθέτουμε κόκκινη γραμμή στο μηδέν της τιμής
# ώστε να είναι εμφανές πότε η τιμή γίνεται αρνητική
ax2.axhline(0, color='red', linewidth=1, linestyle=':')

# Τίτλος και εμφάνιση
plt.title('Το Φαινόμενο του Κανιβαλισμού', fontsize=15, fontweight='bold')
fig.tight_layout()
plt.show()

import pandas as pd
import numpy as np

# ==========================================
# 1. ΦΟΡΤΩΣΗ ΔΕΔΟΜΕΝΩΝ
# ==========================================
#Φόρτωση τιμών
df_prices = pd.read_csv('Price per hour.csv', sep=';', decimal=',')
#Φόρτωση παραγωγής
df_production = pd.read_csv('Energy per hour.csv', sep=';', decimal=',', header=None)

#Καθάρισμα πίνακα παραγωγής
df_production.columns = ['PVsyst_Time', 'Energy_W']
df_production['Energy_MW'] = df_production['Energy_W'] / 1000000
df_production['Datetime'] = pd.date_range(start='2025-01-01 00:00', periods=8760, freq='h')
df_production.set_index('Datetime', inplace=True)

#Καθάρισμα πίνακα τιμών
df_prices.columns = df_prices.columns.str.strip()
time_col = df_prices.columns[0]
price_col = df_prices.columns[1]

df_prices[price_col] = pd.to_numeric(df_prices[price_col].astype(str).str.replace(',', '.'), errors='coerce')
df_prices['Datetime'] = df_prices[time_col].astype(str).str.split(' - ').str[0].str.strip().str[:19]
df_prices['Datetime'] = pd.to_datetime(df_prices['Datetime'], format='%d/%m/%Y %H:%M:%S', errors='coerce')
df_prices.set_index('Datetime', inplace=True)

df_prices_hourly = df_prices.resample('h').mean(numeric_only=True)
df_final = pd.concat([df_production['Energy_MW'], df_prices_hourly[price_col]], axis=1)
df_final.columns = ['Solar_MW', 'Price_EUR_MWh']

# Καθαρίζουμε τα κενά (NaNs)
df_final['Solar_MW'] = df_final['Solar_MW'].fillna(0) # Αν λείπει παραγωγή = 0
df_final['Price_EUR_MWh'] = df_final['Price_EUR_MWh'].ffill().bfill() # Forward fill στις τιμές


# =======================================================
# 2. ΠΡΟΣΟΜΟΙΩΣΗ ΜΠΑΤΑΡΙΑΣ
# =======================================================
BESS_CAPACITY = 3.84   # MWh
BESS_POWER = 2.0   # MW
BESS_AUX_MW = 0.00385 # H ιδιοκατανάλωση της μπαταρίας (3.85 kW)από το PVsyst

grid_static = []
grid_dynamic = []

prices = df_final['Price_EUR_MWh'].values
solar = df_final['Solar_MW'].values

# Α. ΣΤΑΤΙΚΟΣ ΑΛΓΟΡΙΘΜΟΣ (40€ - 120€)
CHARGE_PRICE = 40.0
DISCHARGE_PRICE = 120.0
battery_static = 0.0

for i in range(len(prices)):
    p, s = prices[i], solar[i]
    charge, discharge = 0.0, 0.0

    if p < CHARGE_PRICE and battery_static < BESS_CAPACITY:
        charge = min(BESS_POWER, BESS_CAPACITY - battery_static, s)
        battery_static += charge
    elif p > DISCHARGE_PRICE and battery_static > 0:
        discharge = min(BESS_POWER, battery_static)
        battery_static -= discharge

    net_power = s - charge + discharge - BESS_AUX_MW
    grid_static.append(min(3.5, net_power))

# Β. ΔΥΝΑΜΙΚΟΣ ΑΛΓΟΡΙΘΜΟΣ
df_final['Date'] = df_final.index.date
battery_dynamic = 0.0

for date, daily_data in df_final.groupby('Date'):
    cheapest_threshold = daily_data['Price_EUR_MWh'].nsmallest(2).max()
    expensive_threshold = daily_data['Price_EUR_MWh'].nlargest(2).min()

    for idx, row in daily_data.iterrows():
        p, s = row['Price_EUR_MWh'], row['Solar_MW']
        charge, discharge = 0.0, 0.0

        if p <= cheapest_threshold and battery_dynamic < BESS_CAPACITY:
            charge = min(BESS_POWER, BESS_CAPACITY - battery_dynamic, s)
            battery_dynamic += charge
        elif p >= expensive_threshold and battery_dynamic > 0:
            # Υπολογίζουμε πόσος χώρος υπάρχει στο δίκτυο μέχρι τα 3.5 MW
            available_grid_capacity = max(0.0, 3.5 - s)

            # Η εκφόρτιση περιορίζεται από τη δύναμη του Inverter (2MW),
            #το ρεύμα που έχει μέσα η μπαταρία και τον ελεύθερο χώρο του δικτύου!
            discharge = min(BESS_POWER, battery_dynamic, available_grid_capacity)
            battery_dynamic -= discharge

        net_power = s - charge + discharge - BESS_AUX_MW
        grid_dynamic.append(min(3.5, net_power))

# =======================================================
# 3. ΟΙΚΟΝΟΜΙΚΑ ΑΠΟΤΕΛΕΣΜΑΤΑ
# =======================================================
rev_no_bess = (df_final['Solar_MW'].clip(upper=3.5) * df_final['Price_EUR_MWh']).sum()
rev_static = (np.array(grid_static) * prices).sum()
rev_dynamic = (np.array(grid_dynamic) * prices).sum()

print("📊 ΟΙΚΟΝΟΜΙΚΗ ΑΝΑΛΥΣΗ (PV 5MWp | BESS 3.84 MWh)")
print("=" * 75)
print(f"1. Απλό Πάρκο (Χωρίς Μπαταρία): {rev_no_bess:,.0f} €")
print(f"2. Μπαταρία με Στατικό Αλγόριθμο (40€-120€): {rev_static:,.0f} €  (+ {rev_static - rev_no_bess:,.0f} € έξτρα)")
print(f"3. Μπαταρία με Δυναμικό Αλγόριθμο (Smart): {rev_dynamic:,.0f} €  (+ {rev_dynamic - rev_no_bess:,.0f} € έξτρα)")
print("=" * 75)
print(f"🧠 Αξία Ανάλυσης Δεδομένων (Διαφορά Στατικού-Δυναμικού): +{rev_dynamic - rev_static:,.0f} € !!!")

!pip install pulp

import pulp
import pandas as pd
import numpy as np

print("=" * 60)
print("Εγκαθιστούμε τη βιβλιοθήκη PuLP και ξεκινάμε τη βελτιστοποίηση")
print("=" * 60)

# Βασικές παράμετροι
BESS_CAPACITY = 3.84
BESS_POWER = 2.0
BESS_AUX_MW = 0.00385
T = len(df_final)  # 8760 ώρες

prices = df_final['Price_EUR_MWh'].values
solar = df_final['Solar_MW'].values

# 1. Ορισμός Προβλήματος: Μεγιστοποίηση εσόδων (LpMaximize)
prob = pulp.LpProblem("BESS_Optimal_Arbitrage", pulp.LpMaximize)

# 2. Ορισμός Μεταβλητών Απόφασης
charge = pulp.LpVariable.dicts("Charge", range(T), lowBound=0, upBound=BESS_POWER)
discharge = pulp.LpVariable.dicts("Discharge", range(T), lowBound=0, upBound=BESS_POWER)
soc = pulp.LpVariable.dicts("SoC", range(T), lowBound=0, upBound=BESS_CAPACITY)
# Η μεταβλητή για το ρεύμα που "κόβει" ο Inverter εξαιτίας
# του ορίου έγυχσης στο δίκτυο
curtail = pulp.LpVariable.dicts("Curtail", range(T), lowBound=0)

# 3. Αντικειμενική Συνάρτηση: Συνολικό ετήσιο κέρδος
# Έσοδα = (Ήλιος - Περικοπή - Φόρτιση + Εκφόρτιση - Ιδιοκατανάλωση) * Τιμή
prob += pulp.lpSum([(solar[t] - curtail[t] - charge[t] + discharge[t] - BESS_AUX_MW) * prices[t] for t in range(T)])

# 4. Περιορισμοί
for t in range(T):
    # Περιορισμός Α: Η φόρτιση και η περικοπή δεν μπορούν να ξεπερνούν την διαθέσιμη ενέργεια από τον ήλιο
    prob += charge[t] + curtail[t] <= solar[t], f"Solar_Balance_{t}"

    # Περιορισμός Β: Battery State of Charge
    if t == 0:
        # Την 1η ώρα του έτους: Το SoC είναι απλά Φόρτιση - Εκφόρτιση
        prob += soc[t] == charge[t] - discharge[t], f"SoC_Balance_{t}"
    else:
        # Τις υπόλοιπες ώρες: Νέο SoC = Προηγούμενο SoC + Φόρτιση - Εκφόρτιση
        prob += soc[t] == soc[t-1] + charge[t] - discharge[t], f"SoC_Balance_{t}"

    # Περιορισμός Γ: Grid Power Limit 3.5 MW
    prob += (solar[t] - curtail[t] - charge[t] + discharge[t] - BESS_AUX_MW) <= 3.5, f"Grid_Limit_{t}"

# 5. Λύση
print("Ο αλγόριθμος λύνει την εξίσωση.")
prob.solve()

# 6. Εξαγωγή των βέλτιστων αποτελεσμάτων
optimal_grid = []
for t in range(T):
    c_val = charge[t].varValue
    d_val = discharge[t].varValue
    curt_val = curtail[t].varValue
    optimal_grid.append(solar[t] - curt_val - c_val + d_val - BESS_AUX_MW)

rev_no_bess = (df_final['Solar_MW'].clip(upper=3.5) * df_final['Price_EUR_MWh']).sum()
rev_optimal = (np.array(optimal_grid) * prices).sum()

print("\n📊 ΑΠΟΤΕΛΕΣΜΑΤΑ ΓΡΑΜΜΙΚΟΥ ΠΡΟΓΡΑΜΜΑΤΙΣΜΟΥ (Absolute Optimal)")
print("=" * 70)
print(f"Κατάσταση Επίλυσης:          {pulp.LpStatus[prob.status]}")
print(f"1. Απλό Πάρκο (No BESS):     {rev_no_bess:,.0f} €")
print(f"2. Μαθηματικό Μέγιστο (LP):  {rev_optimal:,.0f} €  (+ {rev_optimal - rev_no_bess:,.0f} € έξτρα)")
print("=" * 70)